index/urls.py
from django.urls import path
from .views import home, chart_view, js_chart, logout_user

urlpatterns = [
    path('', home, name="home"),
    path('chart-view/<str:id>', chart_view, name="chart_view"),
    path('js-chart/<str:id>', js_chart, name="js-chart"),

]

myDay/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),

    path('accounts/', include('allauth.urls')),
]

index/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class chart(models.Model):
    choie = [
        ('Time Chart', 'Time Chart'),
        ('Integer Chart', 'Integer Chart')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    description = models.TextField(blank=True)
    choices = models.CharField(max_length=100, choices=choie)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-date']


class index(models.Model):
    chart = models.ForeignKey(
        chart, related_name="chart_index", blank=True, null=True, on_delete=models.DO_NOTHING)
    int_value = models.IntegerField(blank=True, null=True)
    time_value = models.TimeField(blank=True, null=True)
    date_create = models.DateTimeField(auto_now_add=True)

    @property
    def labels(self):
        return f"{self.date_create:%m/%d}"

    @property
    def time(self):
        return f"{self.time_value:%h}"

    # class Meta:
    #     ordering = ['-date_create']

index/forms.py
from django import forms
from .models import chart, index


class ChartForm(forms.ModelForm):

    class Meta:
        model = chart
        fields = ('name', 'description', 'choices')
        widgets = {
            # 'user': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'choices': forms.Select(attrs={'class': 'form-control'}),
        }


class IndexForm(forms.ModelForm):

    class Meta:
        model = index
        #fields = '__all__'
        fields = ('int_value', 'time_value')

index/views.py
import datetime
from operator import mul

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render

from .forms import ChartForm, IndexForm
from .models import chart, index

# Create your views here.


@login_required(login_url="/accounts/login/")
def home(request):
    chart_data = chart.objects.filter(user=request.user.id)

    if request.method == 'POST':
        form = ChartForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.user = request.user
            data.save()
            return redirect('home')

    form = ChartForm()

    context = {'cr': chart_data, 'form': form}
    return render(request, 'app/index.html', context)


@login_required(login_url="/accounts/login/")
def chart_view(request, id):
    chart_data = chart.objects.get(id=id)
    chart_item = chart_data.chart_index.all().order_by('-date_create')

    if request.user != chart_data.user:
        return HttpResponse("PAGE NOT FOUND")
    if request.method == 'POST':
        form = IndexForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.chart = chart_data
            data.save()

            return redirect('chart_view', id=id)

    context = {'char': chart_data, 'chart_item': chart_item}
    return render(request, 'app/chart-view.html', context)


def logout_user(request):
    logout(request)
    return redirect("/accounts/login/")


@login_required(login_url="/accounts/login/")
def js_chart(request, id):
    jsObj = []
    chart_data = chart.objects.get(id=id)
    json_chart = chart_data.chart_index.all().order_by('-date_create')

    for i in json_chart:
        if chart_data.choices == 'Time Chart':
            my_time = i.time_value
            my_time = str(my_time)
            print(my_time)
            factors = (60, 1, 1/60)
            t1 = sum(ti*j for ti, j in zip(map(int, my_time.split(':')), factors))
            jsObj.append({i.labels: t1})
        elif chart_data.choices == 'Integer Chart':
            jsObj.append({i.labels: i.int_value})
    jsObj = jsObj[:10]
    return JsonResponse(jsObj, safe=False)

templates/app/chart-view.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content-wrapper">
  <br><br><br>
  <section class="content">
    <div class="container-fluid">

      <div class="card">
        <div class="card-body">
          <h5 class="card-title"> {{char.name}} Chart</h5>

          <!-- Line Chart -->
          <canvas id="lineChart" style="max-height: 400px;"></canvas>
          <script>
            let chartData = {
              'date': [],
              'value': [],
            }
            let url = `/js-chart/{{char.id}}`

            fetch(url)
              .then((resp => resp.json()))
              .then(function (data) {
                console.log('Data: ', data)
                let list = data

                for (let i in data) {
                  let date = Object.keys(list[i])[0]
                  let value = Object.values(list[i])[0]
                  chartData.date.push(date)
                  chartData.value.push(value)
                }
                console.log('chartData: ', typeof chartData.value[0])
              })

            document.addEventListener("DOMContentLoaded", () => {
              new Chart(document.querySelector('#lineChart'), {
                type: 'line',
                data: {
                  labels: chartData.date,
                  datasets: [{
                    label: 'Line Chart',
                    data: chartData.value,
                    fill: false,
                    borderColor: 'rgb(75, 192, 192)',
                    tension: 0.1
                  }]
                },
                options: {
                  scales: {
                    y: {
                      beginAtZero: true
                    }
                  }
                }
              });
            });
          </script>
          <!-- End Line CHart -->

        </div>
      </div>
      <!-- form element -->
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <form method="post">
                {% csrf_token %}
                <input type="number" name="int_value" id="id_int_value" class="form-control"
                  placeholder="Enter Integer">
                <input type="time" name="time_value" id="id_time_value" class="form-control" placeholder="Enter Time">
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
              <div class="card-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <br>
                  <div class="input-group-append">
                    <button type="submit" class="btn btn-default">
                      <i class="fas fa-search"></i>
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 300px;">
              <table class="table table-head-fixed text-nowrap">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>index</th>
                    <th>Date</th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in chart_item %}
                  <tr>
                    <td> {{item.id}} </td>
                    {% if char.choices == 'Time Chart' %}
                    <td>{{item.time_value}}</td>
                    {% else %}
                    <td>{{item.int_value}}</td>
                    {% endif %}
                    <td>{{item.date_create}}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
      <!-- /.card --> 
    </div>
  </section>
</div>
<script>
  let choice = `{{char.choices}}`
  console.log(choice)
  if (choice === 'Time Chart') {
    document.getElementById("id_int_value").classList.add('hidden')

  } else if (choice === 'Integer Chart') {
    document.getElementById("id_time_value").classList.add('hidden')

  }
</script>
{% endblock %}

templates/app/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content-wrapper">
  <br><br>
  <section class="content">
    <div class="container-fluid">
      <!-- /.row -->
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Responsive Hover Table</h3>

              <div class="card-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <div class="input-group-append">
                    <button type="submit" class="btn btn-default">
                      <i class="fas fa-search"></i>
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
              <table class="table table-hover text-nowrap">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>title</th>
                    <th>Date</th>
                    <th>Choices</th>
                    <th>Description {{request.user.chart}} </th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in cr %}
                  <tr>
                    <td>{{item.id}}</td>
                    <td><a class="nav-link" href="{% url 'chart_view' item.id %}" role="button">{{item.name}}</a></td>
                    <td>{{item.date}}</td>
                    <td><span class="tag tag-success">{{item.choices}}</span></td>
                    <td>{{item.description}}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
      <!-- /.row -->
    </div>
  </section>
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- jquery validation -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Create New Item</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post">
              {% csrf_token %}
              <div class="card-body">
                {{form}}
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
          </div>
          <!-- /.card-body -->
          </form>
        </div>
        <!-- /.card -->
      </div>
      <!--/.col (left) -->
      <!-- right column -->
      <div class="col-md-6">

      </div>
      <!--/.col (right) -->
    </div>
    <!-- /.row -->
</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> {% block title %}MY DAY{% endblock title %} </title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <style>
    .hidden{
      display: none;
    }
  </style>
</head>

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">

    {% include 'parts/navbar.html' %}

    <!-- Content Wrapper. Contains page content -->
    {% block content %}
    {% endblock %}
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
      All rights reserved.
      <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.1.0
      </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->

  <!-- jQuery UI 1.11.4 -->
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button) 
  </script>
  <!-- ChartJS -->
  <script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
  <!-- Sparkline -->

</body>

</html>

templates/parts/navbar.html
{% load static %}



<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><h5>menu</h5></a>
    </li>

  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
        <i class="fas fa-th-large"></i>
      </a>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Sidebar -->
  <div class="sidebar">

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
        <li class="nav-item menu-open">
          {% if user.is_authenticated %}
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'home' %}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Home</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account_logout' %}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>LOGOUT</p>
              </a>
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{% url 'account_logout' %}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>LOGIN</p>
              </a>
            </li>
            {% endif %}
          </ul>
        </li>

      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>